FROM node:16-alpine AS build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest


COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./conf/nginx.conf  /etc/nginx/conf.d/default.conf

CMD ["nginx","-g", "daemon off;"]
