name: Approval Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  approval_jobs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up GitHub CLI
      #   run: |
      #     curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      #     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      #     sudo apt update
      #     sudo apt install gh
      # - name: Install jq
      #   run: sudo apt-get install jq

      # - name: Create GitHub Issue for Approval
      #   id: issue
      #   run: |
      #     ISSUE_TITLE="Approval Needed for Next Step"
      #     ISSUE_BODY="Please comment 'approve' on this issue to proceed with the third workflow."
      #     issue_response=$(gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "ManualApproval" --assignee "MdShimulMahmud")
      #     echo "Raw issue response: $issue_response"
      #     issue_number=$(echo "$issue_response" | grep -oE 'https://github.com/.*/issues/[0-9]+' | grep -oE '[0-9]+$')
      #     if [ -z "$issue_number" ]; then
      #       echo "Failed to extract issue number."
      #       exit 1
      #     fi
      #     echo "::set-output name=issue_number::$issue_number"
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Wait for approval comment
        uses: ekeel/approval-action@v1.0.3
        id: approval
        with:
          token: ${{ secrets.GH_TOKEN }}
          approvers: 'MdShimulMahmud'
          minimumApprovals: '1'
          issueTitle: 'Approval Needed for Next Step'
          issueBody: 'Please comment "approve" to proceed with the third workflow.'
          issueLabels: 'ManualApproval'
          excludeInitiator: 'false'
          approveWords: 'approve, approved'
          rejectWords: 'deny, denied, reject, rejected'
          waitInterval: '1'
          waitTimeout: '60'

      - name: Store approval status as environment variable
        run: |
          echo "APPROVED=${{ steps.approval.outputs.approved }}" >> $GITHUB_ENV

      - name: Output approval status
        run: |
          echo "Approval status: ${{ steps.approval.outputs.approved }}"
