name: Approval Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if the Build Workflow is successful

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh  # Install GitHub CLI
        # Install jq as well if not already installed, since it's used for extracting issue number
      - name: Install jq (if not available)
        run: sudo apt-get install jq

      - name: Create GitHub Issue for Approval
        id: issue
        run: |
          ISSUE_TITLE="Approval Needed for Next Step"
          ISSUE_BODY="Please comment 'approve' on this issue to proceed with the third workflow."
          issue_response=$(gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "ManualApproval" --assignee "MdShimulMahmud")  # Change to a valid GitHub username
          issue_number=$(echo "$issue_response" | jq -r .number)
          echo "::set-output name=issue_number::$issue_number"  # Output the issue number
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Provide the GitHub token for authentication

      - name: Wait for approval comment
        uses: ekeel/approval-action@v1.0.3
        id: approval
        with:
          token: ${{ secrets.GH_TOKEN }}
          approvers: 'your-github-username'  # Approver's GitHub username
          minimumApprovals: '1'
          issueTitle: 'Approval Needed for Next Step'
          issueBody: 'Please comment "approve" to proceed with the third workflow.'
          issueLabels: 'ManualApproval'
          excludeInitiator: 'false'
          approveWords: 'approve, approved'
          rejectWords: 'deny, denied, reject, rejected'
          waitInterval: '1'
          waitTimeout: '5'

      - name: Store the approval output as an environment variable
        run: |
          echo "APPROVED=${{ steps.approval.outputs.approved }}" >> $GITHUB_ENV

      - name: Output approval status
        run: |
          echo "Approval status: ${{ steps.approval.outputs.approved }}"
