name: Approval Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  approval_jobs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for approval comment
        uses: ekeel/approval-action@v1.0.3
        id: approval
        with:
          token: ${{ secrets.GH_TOKEN }}
          approvers: 'MdShimulMahmud'
          minimumApprovals: '1'
          issueTitle: 'Approval Needed for Next Step'
          issueBody: 'Please comment "approve" to proceed with the third workflow.'
          issueLabels: 'ManualApproval'
          excludeInitiator: 'false'
          approveWords: 'approve, approved'
          rejectWords: 'deny, denied, reject, rejected'
          waitInterval: '1'
          waitTimeout: '60'

      - name: Store approval status as environment variable
        run: |
          echo "APPROVED=${{ steps.approval.outputs.approved }}" >> $GITHUB_ENV

      - name: Output approval status
        run: |
          echo "Approval status: ${{ steps.approval.outputs.approved }}"
