name: Approval Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      approval: ${{ steps.approval.outputs.approved }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Approval Action
        uses: ekeel/approval-action@v1.0.3
        id: approval
        with:
          token: ${{ secrets.GH_TOKEN }}  # GitHub Token for authentication
          approvers: 'MdShimulMahmud'    # Username of the approver
          minimumApprovals: '1'          # Minimum number of approvals needed
          issueTitle: 'Approval Required for Next Step'
          issueBody: 'Please comment "approve" to proceed with the workflow.'
          issueLabels: 'ManualApproval,ApprovalAction'
          excludeInitiator: 'false'      # Include the initiator in the approval process
          approveWords: 'approve, approved'  # Keywords that approve the request
          rejectWords: 'deny, denied, reject, rejected'  # Keywords that reject the request
          waitInterval: '1'  # Interval to check for new comments (in minutes)
          waitTimeout: '5'   # Timeout in minutes before giving up on approval

      - name: Store the approval output as an environment variable
        run: |
          echo "APPROVED=${{ steps.approval.outputs.approved }}" >> $GITHUB_ENV

      - name: Get the approval output
        run: |
          echo "Approved: ${{ steps.approval.outputs.approved }}"
          echo "Approval status is stored in environment variable: $APPROVED"
        env:
          GH_TOKEN: ${{ github.token }} 
