name: Conditional Workflow
on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approval for Deployment'
        required: true
        default: 'no'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'yes' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying to production"
          # Add your deployment commands here
