name: Build CI with GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.check.outputs.current_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          cd ./backend
          npm install

      - name: Debug Run Number
        run: echo "Current Run Number = ${{ github.run_number }}"

      - name: Check current version
        id: check
        run: |
          # Read the current version from the VERSION file
          current_version=$(cat VERSION)
          echo "Current version: $current_version"

          # Set the current_version as an output
          echo "::set-output name=current_version::$current_version"

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    outputs:
      current_version: ${{ steps.check.outputs.current_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: |
          cd ./frontend
          npm install
          npm run build

      - name: Debug Run Number
        run: echo "Current Run Number = ${{ github.run_number }}"

      - name: Check current version
        id: check
        run: |
          # Read the current version from the VERSION file
          current_version=$(cat VERSION)
          echo "Current version: $current_version"

          # Set the current_version as an output
          echo "::set-output name=current_version::$current_version"

  docker:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend:${{ needs.backend.outputs.current_version }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend:${{ needs.backend.outputs.current_version }}
            
      - name: Update Kubernetes Deployment with new image tag
        run: |
          echo "Updating Kubernetes deployment image tags with current version: ${{ needs.backend.outputs.current_version }}"

          # Use sed to replace frontend and backend image tags in k8s/deployment.yaml
          sed -i 's|shimulmahmud/frontend:v[0-9]*\.[0-9]*\.[0-9]*|shimulmahmud/frontend:${{ needs.backend.outputs.current_version }}|' k8s/deployment.yaml
          sed -i 's|shimulmahmud/backend:v[0-9]*\.[0-9]*\.[0-9]*|shimulmahmud/backend:${{ needs.backend.outputs.current_version }}|' k8s/deployment.yaml

          # Optional: Print updated deployment.yaml for debugging
          cat k8s/deployment.yaml